# Generated by Django 2.2.1 on 2019-07-26 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fb_post', '0001_squashed_0002_auto_20190726_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mobile_number',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
    ]
