# Generated by Django 2.2.1 on 2019-07-17 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fb_post', '0002_auto_20190716_1609'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post_created_date',
            new_name='post_create_date',
        ),
    ]
