# Generated by Django 2.2.1 on 2019-07-26 17:59

from django.db import migrations

def combine_names(apps, schema_editor):
    Person = apps.get_model('fb_post', 'Person')
    for person in Person.objects.all():
        person.name = person.first_name + " " + person.last_name
        person.save()

class Migration(migrations.Migration):

    dependencies = [
        ('fb_post', '0004_person'),
    ]

    operations = [
        migrations.RunPython(combine_names),
    ]
