# Generated by Django 2.2.1 on 2019-07-26 18:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('fb_post', '0005_auto_20190726_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='person_id',
            field=models.CharField(default=uuid.UUID('53127da8-1ef5-46ca-8433-a31bbd5c9504'), max_length=500, unique=True),
        ),
    ]
