# Generated by Django 2.2.1 on 2019-07-27 10:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('fb_post_v2', '0004_auto_20190727_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('6e48dc30-c130-43f9-890b-2ab2882b61ad'), unique=True),
        ),
    ]
