# Generated by Django 2.2.1 on 2019-07-27 10:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('fb_post_v2', '0006_auto_20190727_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='uuid',
            field=models.UUIDField(auto_created=uuid.UUID('00bb13c7-71ab-4d75-ac03-677a3be989ef'), unique=True),
        ),
    ]
