# Generated by Django 2.2.1 on 2019-07-27 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fb_post_v2', '0008_auto_20190727_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='uuid',
            field=models.UUIDField(unique=True),
        ),
    ]
